/**
 * Hometown from a free-text GitHub `location` (GRANDPLAN v2 §8, V2-D6). Identity only: a flag on
 * the profile and a world ranking page, never a position in the city. Runs on the trusted fetcher;
 * the lookup tables (geo-data.ts, from GeoNames) are too big to load inside the Worker.
 */

export interface Home {
  /** ISO 3166-1 alpha-2 */
  cc: string;
  city: string | null;
}

/** Lowercase ASCII words: "São Paulo, BR" → "sao paulo br". */
export function geoKey(s: string): string {
  return s
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9']+/g, ' ')
    .replace(/'/g, '')
    .trim();
}

const NOWHERE = new Set(
  [
    'earth',
    'planet earth',
    'world',
    'worldwide',
    'the world',
    'global',
    'remote',
    'anywhere',
    'everywhere',
    'internet',
    'the internet',
    'online',
    'home',
    'localhost',
    '127 0 0 1',
    'moon',
    'mars',
    'the moon',
    'github',
    'cloud',
    'the cloud',
    'nowhere',
    'here',
    'somewhere',
    'universe',
    'milky way',
    'solar system',
  ].map(geoKey),
);

interface Tables {
  countries: Map<string, string>;
  regions: Map<string, string>;
  cities: Map<string, { cc: string; name: string; pop: number }[]>;
}

let tables: Tables | null = null;

async function load(): Promise<Tables | null> {
  if (tables) return tables;
  // generated by scripts/geo-build.ts and not committed (1.4 MB); without it, nobody gets a hometown
  // (a variable specifier, so a fresh clone without the file still typechecks)
  const file = './geo-data.js';
  const data = (await import(/* @vite-ignore */ file).catch(() => null)) as {
    COUNTRY_KEYS: string;
    REGION_KEYS: string;
    CITY_KEYS: string;
  } | null;
  if (!data) return null;
  const { COUNTRY_KEYS, REGION_KEYS, CITY_KEYS } = data;
  const kv = (s: string) => new Map(s.split('\n').map((l) => l.split('\t') as [string, string]));
  const cities = new Map<string, { cc: string; name: string; pop: number }[]>();
  for (const l of CITY_KEYS.split('\n')) {
    const [key, list] = l.split('\t');
    cities.set(
      key!,
      list!.split('|').map((e) => {
        const [cc, name, pop] = e.split(':');
        return { cc: cc!, name: name!, pop: Number(pop) };
      }),
    );
  }
  tables = { countries: kv(COUNTRY_KEYS), regions: kv(REGION_KEYS), cities };
  return tables;
}

function flagCc(s: string): string | null {
  const cps = [...s].map((c) => c.codePointAt(0)!);
  for (let i = 0; i + 1 < cps.length; i++) {
    const a = cps[i]! - 0x1f1e6;
    const b = cps[i + 1]! - 0x1f1e6;
    if (a >= 0 && a < 26 && b >= 0 && b < 26)
      return String.fromCharCode(65 + a) + String.fromCharCode(65 + b);
  }
  return null;
}

/**
 * Parse a location. Rules, in order: a flag emoji or a country name decides the country; a US-style
 * region ("CA", "Bavaria") hints it; a city is taken from the parts before the country, preferring
 * one in that country; with no country, a city must be big (≥ 100k) to count, so "Home" or a pun
 * does not land someone in a small town.
 */
export async function parseLocation(raw: string | null | undefined): Promise<Home | null> {
  if (!raw) return null;
  const t = await load();
  if (!t) return null;
  const text = raw.slice(0, 120);
  const parts = text
    .split(/[,/|;·•()\n]+|\s[-–—]\s|\s@\s|\bor\b|&/)
    .map(geoKey)
    .filter((p) => p && !NOWHERE.has(p));
  if (!parts.length && !flagCc(text)) return null;

  let cc: string | null = flagCc(text);
  let hint: string | null = null;
  const cityParts: string[] = [];
  for (const p of parts) {
    const c = t.countries.get(p);
    if (c && !cc) {
      cc = c;
      continue;
    }
    if (c) continue;
    // "berlin germany": a country as the trailing words of one part
    const words = p.split(' ');
    let split = false;
    for (let k = Math.min(4, words.length - 1); k >= 1 && !split; k--) {
      const tail = words.slice(-k).join(' ');
      const head = words.slice(0, -k).join(' ');
      const tc = t.countries.get(tail) ?? null;
      const tr = tc ? null : (t.regions.get(tail) ?? null);
      if ((tc || tr) && t.cities.has(head)) {
        if (tc) cc ??= tc;
        else hint ??= tr;
        cityParts.push(head);
        split = true;
      }
    }
    if (split) continue;
    const r = t.regions.get(p);
    if (r && !t.cities.has(p)) {
      hint ??= r;
      continue;
    }
    cityParts.push(p);
  }
  const want = cc ?? hint;
  for (const p of cityParts) {
    const list = t.cities.get(p);
    if (!list) continue;
    const inCc = want ? list.find((c) => c.cc === want) : null;
    if (inCc) return { cc: inCc.cc, city: inCc.name };
    if (!cc && list[0]!.pop >= 100_000) return { cc: list[0]!.cc, city: list[0]!.name };
  }
  return cc ? { cc, city: null } : hint ? { cc: hint, city: null } : null;
}
