/**
 * Builds the hometown lookup (GRANDPLAN v2 §8) from GeoNames dumps (CC BY 4.0, geonames.org):
 *   cities15000.txt, countryInfo.txt, admin1CodesASCII.txt from download.geonames.org/export/dump
 *   pnpm tsx scripts/geo-build.ts <dir with the three files>
 * Writes packages/ingest/src/geo-data.ts (used on the trusted fetcher only, never in the Worker)
 * and packages/shared/src/countries.ts (ISO code → name, small enough for the Worker).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { geoKey } from '../packages/ingest/src/geo.ts';

const dir = process.argv[2];
if (!dir) throw new Error('usage: geo-build.ts <geonames dir>');
const lines = (f: string) =>
  readFileSync(join(dir, f), 'utf8')
    .split('\n')
    .filter((l) => l && !l.startsWith('#'));

// countries: ISO2, name, plus common aliases people write in a GitHub location
const names: Record<string, string> = {};
const countryKeys = new Map<string, string>();
for (const l of lines('countryInfo.txt')) {
  const c = l.split('\t');
  const [iso2, iso3, , , name] = c;
  if (!iso2 || !name) continue;
  names[iso2] = name;
  countryKeys.set(geoKey(name), iso2);
  countryKeys.set(geoKey(iso3!), iso2);
}
const ALIASES: Record<string, string[]> = {
  US: ['usa', 'us', 'u s a', 'u s', 'united states of america', 'america'],
  GB: ['uk', 'u k', 'england', 'scotland', 'wales', 'northern ireland', 'great britain', 'britain'],
  DE: ['deutschland'],
  NL: ['the netherlands', 'holland', 'nederland'],
  CN: ['prc', "people's republic of china", 'zhongguo'],
  KR: ['korea', 'south korea', 'republic of korea'],
  RU: ['russian federation', 'rossiya'],
  CZ: ['czech republic', 'czechia'],
  ES: ['espana'],
  BR: ['brasil'],
  MX: ['mexico'],
  JP: ['nippon'],
  IT: ['italia'],
  CH: ['schweiz', 'suisse', 'svizzera'],
  AT: ['osterreich'],
  VN: ['viet nam'],
  TR: ['turkiye'],
  AE: ['uae'],
  CI: ["cote d'ivoire", 'ivory coast'],
  TW: ['taiwan roc', 'republic of china'],
  HK: ['hong kong sar'],
  IR: ['iran'],
  SE: ['sverige'],
  NO: ['norge'],
  DK: ['danmark'],
  FI: ['suomi'],
  PL: ['polska'],
  BE: ['belgie', 'belgique'],
  IN: ['bharat'],
};
for (const [cc, list] of Object.entries(ALIASES))
  for (const a of list) countryKeys.set(geoKey(a), cc);

// regions: US states, Canadian provinces, etc. point at their country ("Austin, TX")
const regions = new Map<string, string>();
for (const r of [
  'bay area',
  'sf bay area',
  'san francisco bay area',
  'silicon valley',
  'socal',
  'norcal',
])
  regions.set(geoKey(r), 'US');
for (const l of lines('admin1CodesASCII.txt')) {
  const [code, name, ascii] = l.split('\t');
  const cc = code!.split('.')[0]!;
  if (!['US', 'CA', 'AU', 'IN', 'BR', 'CN', 'DE', 'GB', 'MX', 'ES', 'IT', 'FR', 'JP'].includes(cc))
    continue;
  for (const n of [name, ascii]) if (n) regions.set(geoKey(n), cc);
  if (cc === 'US' || cc === 'CA' || cc === 'AU') regions.set(geoKey(code!.split('.')[1]!), cc);
}

// cities: best (most populous) per name per country; big cities also keep ASCII alternate names
const cities = new Map<string, Map<string, [string, number]>>();
const add = (key: string, cc: string, name: string, pop: number) => {
  if (!key || key.length < 2) return;
  let m = cities.get(key);
  if (!m) cities.set(key, (m = new Map()));
  const cur = m.get(cc);
  if (!cur || cur[1] < pop) m.set(cc, [name, pop]);
};
for (const l of lines('cities15000.txt')) {
  const c = l.split('\t');
  const name = c[1]!;
  const ascii = c[2]!;
  const alts = c[3]!;
  const cc = c[8]!;
  const pop = Number(c[14]) || 0;
  add(geoKey(name), cc, name, pop);
  add(geoKey(ascii), cc, name, pop);
  if (pop >= 1_000_000)
    for (const a of alts.split(','))
      if (/^[\x20-\x7e]{3,30}$/.test(a)) add(geoKey(a), cc, name, pop);
}

// compact: one line per key, "key\tCC:Name:pop|CC:Name:pop"
const cityLines: string[] = [];
for (const [key, m] of [...cities].sort()) {
  if (countryKeys.has(key)) continue; // "Singapore", "Monaco": the country wins, the city follows
  const list = [...m].sort((a, b) => b[1][1] - a[1][1]).slice(0, 4);
  cityLines.push(
    `${key}\t${list.map(([cc, [n, p]]) => `${cc}:${n.replace(/[|:\t\n]/g, ' ')}:${p}`).join('|')}`,
  );
}
const kv = (m: Map<string, string>) =>
  [...m]
    .sort()
    .map(([k, v]) => `${k}\t${v}`)
    .join('\n');

writeFileSync(
  'packages/ingest/src/geo-data.ts',
  `// Generated by scripts/geo-build.ts from GeoNames (CC BY 4.0, https://www.geonames.org). Do not edit.
export const COUNTRY_KEYS = ${JSON.stringify(kv(countryKeys))};
export const REGION_KEYS = ${JSON.stringify(kv(regions))};
export const CITY_KEYS = ${JSON.stringify(cityLines.join('\n'))};
`,
);
writeFileSync(
  'packages/shared/src/countries.ts',
  `// Generated by scripts/geo-build.ts from GeoNames (CC BY 4.0, https://www.geonames.org). Do not edit.
export const COUNTRY_NAME: Record<string, string> = ${JSON.stringify(names, null, 0)};

/** The flag emoji for an ISO 3166-1 alpha-2 code. */
export const flag = (cc: string) =>
  String.fromCodePoint(...[...cc.toUpperCase()].map((c) => 0x1f1e6 + c.charCodeAt(0) - 65));
`,
);
console.log(
  `countries ${countryKeys.size}, regions ${regions.size}, city keys ${cityLines.length}`,
);
